name: lftsad
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - contourpy=1.3.2
  - cycler=0.12.1
  - expat=2.7.3
  - fonttools=4.61.1
  - freetype=2.14.1
  - glib=2.84.4
  - glib-tools=2.84.4
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - icu=75.1
  - joblib=1.5.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang13=21.1.8
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libglib=2.84.4
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libogg=1.3.5
  - libpng=1.6.54
  - libsqlite=3.51.2
  - libtiff=4.7.0
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.16
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - mkl=2025.3.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - openjpeg=2.5.3
  - openssl=3.6.0
  - packaging=25.0
  - pcre2=10.46
  - pip=25.3
  - ply=3.11
  - pthread-stubs=0.4
  - pyparsing=3.3.1
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytz=2025.2
  - qt-main=5.15.15
  - scikit-learn=1.2.2
  - setuptools=80.9.0
  - sip=6.10.0
  - six=1.17.0
  - sqlite=3.51.1
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - toml=0.10.2
  - tomli=2.4.0
  - tornado=6.5.4
  - ucrt=10.0.22621.0
  - unicodedata2=17.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - arch==6.1.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - dask==2025.12.0
      - distributed==2025.12.0
      - einops==0.6.1
      - fsspec==2026.1.0
      - git-filter-repo==2.47.0
      - hurst==0.0.5
      - idna==3.11
      - importlib-metadata==8.7.1
      - jinja2==3.1.6
      - llvmlite==0.46.0
      - locket==1.0.0
      - markupsafe==3.0.3
      - more-itertools==10.8.0
      - msgpack==1.1.2
      - numba==0.63.1
      - numpy==1.26.4
      - pandas==2.3.3
      - partd==1.4.2
      - patsy==1.0.2
      - pillow==9.4.0
      - portion==2.6.1
      - prts==1.0.0.3
      - psutil==7.2.1
      - pyarrow==22.0.0
      - pyyaml==6.0.3
      - requests==2.32.5
      - scipy==1.11.4
      - sortedcontainers==2.4.0
      - statsmodels==0.14.0
      - stumpy==1.13.0
      - tblib==3.2.2
      - toolz==1.1.0
      - torch==1.13.0
      - tqdm==4.65.0
      - tsfresh==0.20.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.3
      - zict==3.0.0
      - zipp==3.23.0
prefix: C:\Users\benmi\miniconda3\envs\lftsad
